//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECX.CD.BL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9ad72f55-bc00-4382-873e-0c84d6eb3850")]
        public global::System.Guid EnglishGuid {
            get {
                return ((global::System.Guid)(this["EnglishGuid"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("a8474084-2a17-4432-bd85-adf227c2254c")]
        public global::System.Guid AddNewBankAccountTransType {
            get {
                return ((global::System.Guid)(this["AddNewBankAccountTransType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5c71f1f4-1097-4a6c-93bd-57b5be454628")]
        public global::System.Guid SuspendBankAccountTransType {
            get {
                return ((global::System.Guid)(this["SuspendBankAccountTransType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("594bdc42-a05b-49b8-8ead-af1471ae7bdc")]
        public global::System.Guid CloseBankAccountTransType {
            get {
                return ((global::System.Guid)(this["CloseBankAccountTransType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3e3cfadb-ffb1-4aee-815c-8f7231f40346")]
        public global::System.Guid ResumeBankAccountTransType {
            get {
                return ((global::System.Guid)(this["ResumeBankAccountTransType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3e3cfadb-ffb1-4aee-815c-8f7231f40346")]
        public global::System.Guid ClearingPayInGuid {
            get {
                return ((global::System.Guid)(this["ClearingPayInGuid"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3e3cfadb-ffb1-4aee-815c-8f7231f40346")]
        public global::System.Guid ClearingPayOutGuid {
            get {
                return ((global::System.Guid)(this["ClearingPayOutGuid"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.169:8080/ECXWRFWS-war/UnpledgeService")]
        public string ECX_CD_BL_ECXUnpledge_UnpledgeService1 {
            get {
                return ((string)(this["ECX_CD_BL_ECXUnpledge_UnpledgeService1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int DaysSoldWHRAppearsInPRML {
            get {
                return ((int)(this["DaysSoldWHRAppearsInPRML"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int DaysWithdrawnWHRAppearsInPRML {
            get {
                return ((int)(this["DaysWithdrawnWHRAppearsInPRML"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int DaysUnpledgedWHRAppearsInPRML {
            get {
                return ((int)(this["DaysUnpledgedWHRAppearsInPRML"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.1.5.11:8080/ECXWRFWS-war/PledgeService")]
        public string ECX_CD_BL_ECXPledge_PledgeService {
            get {
                return ((string)(this["ECX_CD_BL_ECXPledge_PledgeService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.1.5.11:8080/ECXWRFWS-war/LNSService")]
        public string ECX_CD_BL_ECXLNS_LNSService {
            get {
                return ((string)(this["ECX_CD_BL_ECXLNS_LNSService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.1.5.11:8080/ECXWRFWS-war/PRMLService")]
        public string ECX_CD_BL_ECXPRML_PRMLService {
            get {
                return ((string)(this["ECX_CD_BL_ECXPRML_PRMLService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.1.5.11:8080/ECXWRFWS-war/transferTitleService")]
        public string ECX_CD_BL_ECXForeclosure_transferTitleService {
            get {
                return ((string)(this["ECX_CD_BL_ECXForeclosure_transferTitleService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7ade2e5c-b98f-4865-ba85-c0e597141236;24a713b3-c9db-41f2-8153-9795ec8eb6bf;5191065" +
            "4-4835-41ca-9129-fce626964d97")]
        public string BanksEngagedInWRF {
            get {
                return ((string)(this["BanksEngagedInWRF"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.1.5.20:5000/ECXLookup/ECXLookup.asmx")]
        public string ECX_CD_BL_ECXLookup_ECXLookup {
            get {
                return ((string)(this["ECX_CD_BL_ECXLookup_ECXLookup"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.1.5.11:8080/ECXWRFWS-war/UnpledgeService")]
        public string ECX_CD_BL_ECXUnpledge_UnpledgeService {
            get {
                return ((string)(this["ECX_CD_BL_ECXUnpledge_UnpledgeService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.1.5.20:5000/ECXEngine/ECXEngine.asmx")]
        public string ECX_CD_BL_ECXEngine_ECXEngine {
            get {
                return ((string)(this["ECX_CD_BL_ECXEngine_ECXEngine"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.1.5.20:5000/ECXSecurity/ECXSecurityAccess.asmx")]
        public string ECX_CD_BL_ECXSecurity_ECXSecurityAccess {
            get {
                return ((string)(this["ECX_CD_BL_ECXSecurity_ECXSecurityAccess"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.1.5.20:5000/WareHouseApplicationWebservice/WebServiceWareHouse.asmx")]
        public string ECX_CD_BL_Warehouse_ECXWarehouse_WebServiceWareHouse {
            get {
                return ((string)(this["ECX_CD_BL_Warehouse_ECXWarehouse_WebServiceWareHouse"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.1.5.8/WarehouseApplication/GRNWRSync.asmx")]
        public string ECX_CD_BL_Warehouse_ECXGRNWR_GRNWRSync {
            get {
                return ((string)(this["ECX_CD_BL_Warehouse_ECXGRNWR_GRNWRSync"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.1.5.20:5000/MembershipLookup/MemberShipLookUp.asmx")]
        public string ECX_CD_BL_ECXMembership_MemberShipLookUp {
            get {
                return ((string)(this["ECX_CD_BL_ECXMembership_MemberShipLookUp"]));
            }
        }
    }
}
