//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36392
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.36392.
// 
#pragma warning disable 1591

namespace ECX.CD.DA.GINDetail {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GINDetailSoap", Namespace="http://tempuri.org/")]
    public partial class GINDetail : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetGINLoadingDetailOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGINScalingDetailOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGINStatusListOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExtendPUNOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGINReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdatePickupAgentOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GINDetail() {
            this.Url = global::ECX.CD.DA.Properties.Settings.Default.ECX_CD_DA_GINDetail_GINDetail;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetGINLoadingDetailCompletedEventHandler GetGINLoadingDetailCompleted;
        
        /// <remarks/>
        public event GetGINScalingDetailCompletedEventHandler GetGINScalingDetailCompleted;
        
        /// <remarks/>
        public event GetGINStatusListCompletedEventHandler GetGINStatusListCompleted;
        
        /// <remarks/>
        public event ExtendPUNCompletedEventHandler ExtendPUNCompleted;
        
        /// <remarks/>
        public event GetGINReportCompletedEventHandler GetGINReportCompleted;
        
        /// <remarks/>
        public event UpdatePickupAgentCompletedEventHandler UpdatePickupAgentCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGINLoadingDetail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CGINLoading GetGINLoadingDetail(System.Guid ginId) {
            object[] results = this.Invoke("GetGINLoadingDetail", new object[] {
                        ginId});
            return ((CGINLoading)(results[0]));
        }
        
        /// <remarks/>
        public void GetGINLoadingDetailAsync(System.Guid ginId) {
            this.GetGINLoadingDetailAsync(ginId, null);
        }
        
        /// <remarks/>
        public void GetGINLoadingDetailAsync(System.Guid ginId, object userState) {
            if ((this.GetGINLoadingDetailOperationCompleted == null)) {
                this.GetGINLoadingDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGINLoadingDetailOperationCompleted);
            }
            this.InvokeAsync("GetGINLoadingDetail", new object[] {
                        ginId}, this.GetGINLoadingDetailOperationCompleted, userState);
        }
        
        private void OnGetGINLoadingDetailOperationCompleted(object arg) {
            if ((this.GetGINLoadingDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGINLoadingDetailCompleted(this, new GetGINLoadingDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGINScalingDetail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CGINScaling GetGINScalingDetail(System.Guid ginId) {
            object[] results = this.Invoke("GetGINScalingDetail", new object[] {
                        ginId});
            return ((CGINScaling)(results[0]));
        }
        
        /// <remarks/>
        public void GetGINScalingDetailAsync(System.Guid ginId) {
            this.GetGINScalingDetailAsync(ginId, null);
        }
        
        /// <remarks/>
        public void GetGINScalingDetailAsync(System.Guid ginId, object userState) {
            if ((this.GetGINScalingDetailOperationCompleted == null)) {
                this.GetGINScalingDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGINScalingDetailOperationCompleted);
            }
            this.InvokeAsync("GetGINScalingDetail", new object[] {
                        ginId}, this.GetGINScalingDetailOperationCompleted, userState);
        }
        
        private void OnGetGINScalingDetailOperationCompleted(object arg) {
            if ((this.GetGINScalingDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGINScalingDetailCompleted(this, new GetGINScalingDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGINStatusList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetGINStatusList() {
            object[] results = this.Invoke("GetGINStatusList", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetGINStatusListAsync() {
            this.GetGINStatusListAsync(null);
        }
        
        /// <remarks/>
        public void GetGINStatusListAsync(object userState) {
            if ((this.GetGINStatusListOperationCompleted == null)) {
                this.GetGINStatusListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGINStatusListOperationCompleted);
            }
            this.InvokeAsync("GetGINStatusList", new object[0], this.GetGINStatusListOperationCompleted, userState);
        }
        
        private void OnGetGINStatusListOperationCompleted(object arg) {
            if ((this.GetGINStatusListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGINStatusListCompleted(this, new GetGINStatusListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ExtendPUN", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ExtendPUN(CExpiredPUNExtension[] punExtensions, System.Guid userId, System.DateTime invocationDateTime) {
            object[] results = this.Invoke("ExtendPUN", new object[] {
                        punExtensions,
                        userId,
                        invocationDateTime});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ExtendPUNAsync(CExpiredPUNExtension[] punExtensions, System.Guid userId, System.DateTime invocationDateTime) {
            this.ExtendPUNAsync(punExtensions, userId, invocationDateTime, null);
        }
        
        /// <remarks/>
        public void ExtendPUNAsync(CExpiredPUNExtension[] punExtensions, System.Guid userId, System.DateTime invocationDateTime, object userState) {
            if ((this.ExtendPUNOperationCompleted == null)) {
                this.ExtendPUNOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExtendPUNOperationCompleted);
            }
            this.InvokeAsync("ExtendPUN", new object[] {
                        punExtensions,
                        userId,
                        invocationDateTime}, this.ExtendPUNOperationCompleted, userState);
        }
        
        private void OnExtendPUNOperationCompleted(object arg) {
            if ((this.ExtendPUNCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExtendPUNCompleted(this, new ExtendPUNCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGINReport", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CGINReport GetGINReport(string ginId) {
            object[] results = this.Invoke("GetGINReport", new object[] {
                        ginId});
            return ((CGINReport)(results[0]));
        }
        
        /// <remarks/>
        public void GetGINReportAsync(string ginId) {
            this.GetGINReportAsync(ginId, null);
        }
        
        /// <remarks/>
        public void GetGINReportAsync(string ginId, object userState) {
            if ((this.GetGINReportOperationCompleted == null)) {
                this.GetGINReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGINReportOperationCompleted);
            }
            this.InvokeAsync("GetGINReport", new object[] {
                        ginId}, this.GetGINReportOperationCompleted, userState);
        }
        
        private void OnGetGINReportOperationCompleted(object arg) {
            if ((this.GetGINReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGINReportCompleted(this, new GetGINReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdatePickupAgent", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdatePickupAgent(string pickupAgentId, string agentName, int nidType, string nidNumber, string agentTel) {
            object[] results = this.Invoke("UpdatePickupAgent", new object[] {
                        pickupAgentId,
                        agentName,
                        nidType,
                        nidNumber,
                        agentTel});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdatePickupAgentAsync(string pickupAgentId, string agentName, int nidType, string nidNumber, string agentTel) {
            this.UpdatePickupAgentAsync(pickupAgentId, agentName, nidType, nidNumber, agentTel, null);
        }
        
        /// <remarks/>
        public void UpdatePickupAgentAsync(string pickupAgentId, string agentName, int nidType, string nidNumber, string agentTel, object userState) {
            if ((this.UpdatePickupAgentOperationCompleted == null)) {
                this.UpdatePickupAgentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdatePickupAgentOperationCompleted);
            }
            this.InvokeAsync("UpdatePickupAgent", new object[] {
                        pickupAgentId,
                        agentName,
                        nidType,
                        nidNumber,
                        agentTel}, this.UpdatePickupAgentOperationCompleted, userState);
        }
        
        private void OnUpdatePickupAgentOperationCompleted(object arg) {
            if ((this.UpdatePickupAgentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdatePickupAgentCompleted(this, new UpdatePickupAgentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36392")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CGINLoading {
        
        private string bagTypeField;
        
        private System.DateTime dateLoadedField;
        
        private int totalNoOfBagsField;
        
        private string remarkField;
        
        private CLoadedStack[] loadedStacksField;
        
        /// <remarks/>
        public string BagType {
            get {
                return this.bagTypeField;
            }
            set {
                this.bagTypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateLoaded {
            get {
                return this.dateLoadedField;
            }
            set {
                this.dateLoadedField = value;
            }
        }
        
        /// <remarks/>
        public int TotalNoOfBags {
            get {
                return this.totalNoOfBagsField;
            }
            set {
                this.totalNoOfBagsField = value;
            }
        }
        
        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
        
        /// <remarks/>
        public CLoadedStack[] LoadedStacks {
            get {
                return this.loadedStacksField;
            }
            set {
                this.loadedStacksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36392")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CLoadedStack {
        
        private string shedField;
        
        private string stackField;
        
        private int noOfBagsField;
        
        private string loadingSupervisorField;
        
        /// <remarks/>
        public string Shed {
            get {
                return this.shedField;
            }
            set {
                this.shedField = value;
            }
        }
        
        /// <remarks/>
        public string Stack {
            get {
                return this.stackField;
            }
            set {
                this.stackField = value;
            }
        }
        
        /// <remarks/>
        public int NoOfBags {
            get {
                return this.noOfBagsField;
            }
            set {
                this.noOfBagsField = value;
            }
        }
        
        /// <remarks/>
        public string LoadingSupervisor {
            get {
                return this.loadingSupervisorField;
            }
            set {
                this.loadingSupervisorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36392")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CGINReport {
        
        private System.Guid gINIdField;
        
        private string gINNumberField;
        
        private System.Nullable<System.DateTime> dateIssuedField;
        
        private System.Nullable<System.Guid> warehouseField;
        
        private System.Nullable<System.Guid> clientIdField;
        
        private string agentNameField;
        
        private System.Nullable<int> nIDTypeField;
        
        private string nIDNumberField;
        
        private System.Nullable<System.Guid> commodityGradeIdField;
        
        private System.Nullable<double> quantityField;
        
        private System.Nullable<double> netWeightField;
        
        private string scaleTicketNumberField;
        
        private System.Nullable<System.Guid> bagTypeField;
        
        private System.Nullable<int> numberOfBagsField;
        
        private string driverNameField;
        
        private string licenseNumberField;
        
        private string licenseIssuedPlaceField;
        
        private string plateNumberField;
        
        private System.Nullable<int> statusField;
        
        /// <remarks/>
        public System.Guid GINId {
            get {
                return this.gINIdField;
            }
            set {
                this.gINIdField = value;
            }
        }
        
        /// <remarks/>
        public string GINNumber {
            get {
                return this.gINNumberField;
            }
            set {
                this.gINNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DateIssued {
            get {
                return this.dateIssuedField;
            }
            set {
                this.dateIssuedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.Guid> Warehouse {
            get {
                return this.warehouseField;
            }
            set {
                this.warehouseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.Guid> ClientId {
            get {
                return this.clientIdField;
            }
            set {
                this.clientIdField = value;
            }
        }
        
        /// <remarks/>
        public string AgentName {
            get {
                return this.agentNameField;
            }
            set {
                this.agentNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> NIDType {
            get {
                return this.nIDTypeField;
            }
            set {
                this.nIDTypeField = value;
            }
        }
        
        /// <remarks/>
        public string NIDNumber {
            get {
                return this.nIDNumberField;
            }
            set {
                this.nIDNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.Guid> CommodityGradeId {
            get {
                return this.commodityGradeIdField;
            }
            set {
                this.commodityGradeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> NetWeight {
            get {
                return this.netWeightField;
            }
            set {
                this.netWeightField = value;
            }
        }
        
        /// <remarks/>
        public string ScaleTicketNumber {
            get {
                return this.scaleTicketNumberField;
            }
            set {
                this.scaleTicketNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.Guid> BagType {
            get {
                return this.bagTypeField;
            }
            set {
                this.bagTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> NumberOfBags {
            get {
                return this.numberOfBagsField;
            }
            set {
                this.numberOfBagsField = value;
            }
        }
        
        /// <remarks/>
        public string DriverName {
            get {
                return this.driverNameField;
            }
            set {
                this.driverNameField = value;
            }
        }
        
        /// <remarks/>
        public string LicenseNumber {
            get {
                return this.licenseNumberField;
            }
            set {
                this.licenseNumberField = value;
            }
        }
        
        /// <remarks/>
        public string LicenseIssuedPlace {
            get {
                return this.licenseIssuedPlaceField;
            }
            set {
                this.licenseIssuedPlaceField = value;
            }
        }
        
        /// <remarks/>
        public string PlateNumber {
            get {
                return this.plateNumberField;
            }
            set {
                this.plateNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36392")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CExpiredPUNExtension {
        
        private System.Guid pickupNoticeIdField;
        
        private int noOfDaysField;
        
        /// <remarks/>
        public System.Guid PickupNoticeId {
            get {
                return this.pickupNoticeIdField;
            }
            set {
                this.pickupNoticeIdField = value;
            }
        }
        
        /// <remarks/>
        public int NoOfDays {
            get {
                return this.noOfDaysField;
            }
            set {
                this.noOfDaysField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36392")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CReturnedBag {
        
        private string shedField;
        
        private string stackField;
        
        private int noOfBagsField;
        
        private decimal sizeField;
        
        /// <remarks/>
        public string Shed {
            get {
                return this.shedField;
            }
            set {
                this.shedField = value;
            }
        }
        
        /// <remarks/>
        public string Stack {
            get {
                return this.stackField;
            }
            set {
                this.stackField = value;
            }
        }
        
        /// <remarks/>
        public int NoOfBags {
            get {
                return this.noOfBagsField;
            }
            set {
                this.noOfBagsField = value;
            }
        }
        
        /// <remarks/>
        public decimal Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36392")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CGINScaling {
        
        private System.DateTime dateWeighedField;
        
        private string scaleTicketNoField;
        
        private decimal truckWeightField;
        
        private decimal grossWeightField;
        
        private string weighingSupervisorField;
        
        private string remarkField;
        
        private CReturnedBag[] returnedBagsField;
        
        /// <remarks/>
        public System.DateTime DateWeighed {
            get {
                return this.dateWeighedField;
            }
            set {
                this.dateWeighedField = value;
            }
        }
        
        /// <remarks/>
        public string ScaleTicketNo {
            get {
                return this.scaleTicketNoField;
            }
            set {
                this.scaleTicketNoField = value;
            }
        }
        
        /// <remarks/>
        public decimal TruckWeight {
            get {
                return this.truckWeightField;
            }
            set {
                this.truckWeightField = value;
            }
        }
        
        /// <remarks/>
        public decimal GrossWeight {
            get {
                return this.grossWeightField;
            }
            set {
                this.grossWeightField = value;
            }
        }
        
        /// <remarks/>
        public string WeighingSupervisor {
            get {
                return this.weighingSupervisorField;
            }
            set {
                this.weighingSupervisorField = value;
            }
        }
        
        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
        
        /// <remarks/>
        public CReturnedBag[] ReturnedBags {
            get {
                return this.returnedBagsField;
            }
            set {
                this.returnedBagsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void GetGINLoadingDetailCompletedEventHandler(object sender, GetGINLoadingDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGINLoadingDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGINLoadingDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CGINLoading Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CGINLoading)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void GetGINScalingDetailCompletedEventHandler(object sender, GetGINScalingDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGINScalingDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGINScalingDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CGINScaling Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CGINScaling)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void GetGINStatusListCompletedEventHandler(object sender, GetGINStatusListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGINStatusListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGINStatusListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void ExtendPUNCompletedEventHandler(object sender, ExtendPUNCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExtendPUNCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExtendPUNCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void GetGINReportCompletedEventHandler(object sender, GetGINReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGINReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGINReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CGINReport Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CGINReport)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void UpdatePickupAgentCompletedEventHandler(object sender, UpdatePickupAgentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdatePickupAgentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdatePickupAgentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591